### ISSUE TITLE
Makefile parser error: syntax error, unexpected ), expecting CHARS or VAR or $(

### ISSUE THREAD

**Issue by tritao** [xaizek/zograscope#5]
```
../nuttx/arch/sim/src/Makefile:268:9: parse error: syntax error, unexpected ), expecting CHARS or VAR or $(
Failed to parse: ../nuttx/arch/sim/src/Makefile
```

Points to this:

```
ifeq ($())CONFIG_SIM_CYGWIN_DECORATED),y)
```

**Comment by xaizek** [comment]
Not sure if I can make the parser consume this without switching to GLR kind. Or even if I should, as gmake doesn't handle this consistently:
```
ifeq ($())CONFIG_SIM_CYGWIN_DECORATED),y) # OK
ifeq (y,$())CONFIG_SIM_CYGWIN_DECORATED)) # reversed order -- ERROR
```

Either way, this conditional always evaluates to `false` because it compares `)CONFIG_SIM_CYGWIN_DECORATED)` to `y`. Code to check this:
```make
b = )CONFIG_SIM_CYGWIN_DECORATED)

ifeq ($())CONFIG_SIM_CYGWIN_DECORATED),$b)
    $(info match)
endif
```
Output is: `match`. Those `))` shouldn't be there, you might want to fix/report this.

**Comment by tritao** [comment]
Yep not worth it to add so much complexity to parse this one.
I will send a patch to NuttX.

Thanks so much for your work on this.
